name: Feature Request
description: Suggest a new feature or idea for Cheetos
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a game
      description: A clear and concise description of what the problem is. For example, "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want the new feature to do.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or tools you've already tried.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context, mockup designs, or screenshots about the feature request here.
    validations:
      required: false
