name: Build binary without AntiRE

on:
  push:
    branches:
      - withoutAntiRE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MinGW-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 cmake zip jq

      - name: Build Evitania
        run: ./scripts/build

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(jq -r .version config.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare Artifacts
        run: |
          mkdir -p release_pkg
          cp build/release/Evitania.dll release_pkg/
          cd release_pkg
          zip -r ../Evitania-v${{ steps.get_version.outputs.version }}-${{ github.ref_name }}.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Evitania-v${{ steps.get_version.outputs.version }}-${{ github.ref_name }}
          path: Evitania-v${{ steps.get_version.outputs.version }}-${{ github.ref_name }}.zip
