name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install MinGW-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 cmake

      - name: Build Evitania
        run: ./scripts/build.sh

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(jq -r .version version.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare Build Artifacts
        run: |
          mkdir -p release_pkg
          cp build/release/Evitania.dll release_pkg/
          cp build/release/injector.exe release_pkg/
          cp scripts/run.sh release_pkg/
          cp scripts/run.bat release_pkg/
          cp resources/template/README.md release_pkg/README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Evitania-v${{ steps.get_version.outputs.version }}
          path: release_pkg/
